# 使用的语言
language : node_js
# 语言的版本
node_js :
  - 8.0.0

# 项目所在分支
# branches:
#   only:
#   - master

before_install:
- openssl aes-256-cbc -K $encrypted_00d82f712a30_key -iv $encrypted_00d82f712a30_iv -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

# 安装依赖
# install:
# - npm install

# .travis.yml 配置
# cache:
#   directories:
#     - node_modules
