language : node_js
node_js :
  - 8.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_00d82f712a30_key -iv $encrypted_00d82f712a30_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa -f ~/.ssh
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
